### ISSUE TITLE
Addon installs an old version of backstopjs

### ISSUE THREAD

**Issue by Wylbur** [mmunz/ddev-backstopjs#19]
Any way to update this addon to install the latest version of Backstopjs?  The current version is 6.3.25, and the addon is installing 6.3.3.

Thanks!

**Comment by tyler36** [comment]
Hi @Wylbur 

To bump the version:

1. Create `.ddev/docker-compose.backstopCustom.yaml`

```yaml
services:
  backstop:
    build:
      args:
        BASE_IMAGE: backstopjs/backstopjs:6.3.25
        username: $USER
        uid: $DDEV_UID
        gid: $DDEV_GID
    image: backstopjs/backstopjs:6.3.25-${DDEV_SITENAME}-built
```

2. Restart DDEV.


Please consider making a PR to bump the in `docker-compose.backstop.yaml`. The above method is a work-around until the version is "officially" bumped and released.
