### ISSUE TITLE
Could not use it

### ISSUE THREAD

**Issue by XristosD** [mmunz/ddev-backstopjs#7]
I'm trying to use this addon but I get following error:
```
BackstopJS v6.2.2
Loading config:  /src/backstop.json 

COMMAND | Executing core for "test"
createBitmaps | Selected 1 of 1 scenarios.

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.


  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

Cookie state restored with: [
  {
    "path": "/",
    "name": "yourCookieName",
    "value": "yourCookieValue",
    "expirationDate": 1798790400,
    "hostOnly": false,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameSite": "Lax",
    "url": "https://.www.yourdomain.com"
  }
]
Cookie state restored with: [
  {
    "path": "/",
    "name": "yourCookieName",
    "value": "yourCookieValue",
    "expirationDate": 1798790400,
    "hostOnly": false,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameSite": "Lax",
    "url": "https://.www.yourdomain.com"
  }
]
Puppeteer encountered an error while running scenario "homepage"
Error: net::ERR_CONNECTION_REFUSED at https://powerme.ddev.site/
Puppeteer encountered an error while running scenario "homepage"
Error: net::ERR_CONNECTION_REFUSED at https://powerme.ddev.site/
      COMMAND | Executing core for "report"
      compare | Reference image not found powerme_homepage_0__0_phone.png
      compare | Reference image not found powerme_homepage_0__1_tablet.png
       report | Test completed...
       report | 0 Passed
       report | 2 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied json report to: /src/backstop_data/bitmaps_test/20231219-084619/report.json
       report | Copied jsonp report to: /src/backstop_data/html_report/config.js
      COMMAND | Executing core for "openReport"
   openReport | Attempting to ping 
   openReport | Remote not found. Opening backstop_data/html_report/index.html
       report | *** Mismatch errors found ***
      COMMAND | Command "report" ended with an error after [0.084s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:284:17
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
      COMMAND | Command "test" ended with an error after [0.993s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:284:17
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Failed to run backstop test: exit status 1
```
I'm not sure why I get 

> Error: net::ERR_CONNECTION_REFUSED at https://powerme.ddev.site/

When I tried this with not docker internal urls it works as expected

this is my backstop.json:

```
{
  "id": "backstop_default",
  "viewports": [
    {
      "label": "phone",
      "width": 320,
      "height": 480
    },
    {
      "label": "tablet",
      "width": 1024,
      "height": 768
    }
  ],
  "onBeforeScript": "puppet/onBefore.js",
  "onReadyScript": "puppet/onReady.js",
  "scenarios": [
    {
      "label": "homepage",
      "cookiePath": "backstop_data/engine_scripts/cookies.json",
      "url": "https://powerme.ddev.site/",
      "referenceUrl": "https://www.powerme.gr/",
      "readyEvent": "",
      "readySelector": "",
      "delay": 0,
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [],
      "selectorExpansion": true,
      "expect": 0,
      "misMatchThreshold" : 0.1,
      "requireSameDimensions": true
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": ["browser"],
  "engine": "puppeteer",
  "engineOptions": {
    "args": ["--no-sandbox"]
  },
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}

```
Any suggestion on how to solve this?

**Comment by XristosD** [comment]
OK there was an additional configuration step required: 
just set "external_links:" option on "docker-compose.backstop.yaml" so that services can communicate each other.
I think that this step could be added on docs so that it helps non-experienced ddev users like my self.

**Comment by mmunz** [comment]
Hi,

it should add all web container hostnames in the entrypoint: https://github.com/mmunz/ddev-backstopjs/blob/main/backstopBuild/entrypoint.sh

Is the unreachable domain in the same ddev project as ddev-backstop? If so, then i 'm wondering wht it does not work/what i wrong in the entryscript.

**Comment by fede-green** [comment]
I'm having a similar problem i think. 

I am using this in the same ddev project on which i'd like to run the test. I added in the networks section: 

`    networks:
      ddev_default:
      default:
      external_links:
        - "ddev-router:my.site.com.ddev.site" `
        
but when i start ddev i get: 

` validating /path/to/my/folder/.ddev/docker-compose.backstop.yaml: services.backstop.networks.external_links must be a mapping 
`

**Comment by mmunz** [comment]
@fede-green i guess your yaml is broken for some reason. Check linebreaks and indentation, the networks line should span multiple lines, e.g.

```
services:
  web:
    external_links:
      - "ddev-router:projectb.ddev.site"
```

**Comment by fede-green** [comment]
Thank you @mmunz . Sorry i pasted without formatting. Here's my complete docker-compose.backstop.yaml:

```yml
name: my-site-com-backstop
services:
  backstop:
    container_name: ddev-${DDEV_SITENAME}-backstop
    build:
      context: ./backstopBuild
      args:
        BASE_IMAGE: backstopjs/backstopjs:6.3.3
        username: $USER
        uid: $DDEV_UID
        gid: $DDEV_GID
    image: backstopjs/backstopjs:6.3.3-${DDEV_SITENAME}-built
    user: $DDEV_UID:$DDEV_GID
    init: true
    entrypoint:
      - /entrypoint.sh
    volumes:
      - ../tests/backstop:/src
      - .:/mnt/ddev_config:ro
    shm_size: 1gb
    environment:
      DDEV_HOSTNAME: $DDEV_HOSTNAME
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    networks:
      ddev_default:
      default:
      external_links:
        - "ddev-router:my.site.com.ddev.site"
```

**Comment by mmunz** [comment]
@fede-green ah, i see where this wrong config is coming from. There was a misleading comment in the README, i just removed that and also added an example for using external_links.

See https://github.com/mmunz/ddev-backstopjs#how-to-add-additional-hostnames

**Comment by fede-green** [comment]
mhm, sorry, using `docker-compose.external_links.yaml` as suggested in that comment, i get: 
`service "chrome" has neither an image nor a build context specified: invalid compose project`

going back to ddev's FAQ, i kinda got the connection adding a `docker-compose.communicate.yaml` file: 
```
services:
  backstop:
    external_links:
      - "ddev-router:download.tekla.com.ddev.site"
      ```
now i get the connection, but all the tests complain that the certificate is not valid: 
`Error: net::ERR_CERT_AUTHORITY_INVALID `

But now that i read your comment again, i wonder: what if i put the backstop definition in the same file where i have all the other definitions? because i want to test the service i have in the `web` section... i just thought the backstop compose file could be on its own.
